/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const LOGIN_UNI_USER = "LOGIN_UNI_USER";
export const LOGIN_UNI_USER_SUCCESS = "LOGIN_UNI_USER_SUCCESS";
export const LOGIN_UNI_USER_ERROR = "LOGIN_UNI_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const RESET_USER = "RESET_USER";
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS";
export const RESET_USER_ERROR = "RESET_USER_ERROR";
export const FORGET_PASSWORD = "FORGET_PASSWORD";
export const FORGET_PASSWORD_SUCCESS = "FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_ERROR = "FORGET_PASSWORD_ERROR";
export const UNI_FORGET_PASSWORD = "UNI_FORGET_PASSWORD"
export const UNI_FORGET_PASSWORD_SUCCESS = "UNI_FORGET_PASSWORD_SUCCESS"
export const UNI_FORGET_PASSWORD_ERROR = "UNI_FORGET_PASSWORD_ERROR"
export const RECOVER_PASSWORD= "RECOVER_PASSWORD";
export const RECOVER_PASSWORD_SUCCESS= "RECOVER_PASSWORD_SUCCESS";
export const RECOVER_PASSWORD_ERROR= "RECOVER_PASSWORD_ERROR";
export const OTP_RESEND = "OTP_RESEND";
export const OTP_RESEND_SUCCESS = "OTP_RESEND_SUCCESS";
export const OTP_RESEND_ERROR = "OTP_RESEND_ERROR";
export const RESET_PASSWORD="RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR="RESET_PASSWORD_ERROR";
export const SEND_MAGICLINK = "SEND_MAGICLINK";
export const SEND_MAGICLINK_SUCCESS = "SEND_MAGICLINK_SUCCESS";
export const SEND_MAGICLINK_ERROR = "SEND_MAGICLINK_ERROR";
export const MAGIC_LINK_VERIFY = "MAGIC_LINK_VERIFY";
export const MAGIC_LINK_VERIFY_SUCCESS = "MAGIC_LINK_VERIFY_SUCCESS";
export const MAGIC_LINK_VERIFY_ERROR = "MAGIC_LINK_VERIFY_ERROR";

export const VERIFY_EMAIL_LINK = "VERIFY_EMAIL_LINK";
export const VERIFY_EMAIL_LINK_SUCCESS = "VERIFY_EMAIL_LINK_SUCCESS";
export const VERIFY_EMAIL_LINK_ERROR = "VERIFY_EMAIL_LINK_ERROR";

/* Student*/
export const ADD_STUDENT = "ADD_STUDENT";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";
export const ADD_STUDENT_ERROR = "ADD_STUDENT_ERROR";

export const SCHEDULE_CALL = "SCHEDULE_CALL";
export const SCHEDULE_CALL_SUCCESS = "SCHEDULE_CALL_SUCCESS";
export const SCHEDULE_CALL_ERROR = "SCHEDULE_CALL_ERROR";

export const ADD_MENTOR = "ADD_MENTOR";
export const ADD_MENTOR_SUCCESS = "ADD_MENTOR_SUCCESS";
export const ADD_MENTOR_ERROR = "ADD_MENTOR_ERROR";

export const GET_MENTOR_DETAILS = "GET_MENTOR_DETAILS";
export const GET_MENTOR_DETAILS_SUCCESS = "GET_MENTOR_DETAILS_SUCCESS";
export const GET_MENTOR_DETAILS_ERROR = "GET_MENTOR_DETAILS_ERROR";

export const UPDATE_STUDENT = "UPDATE_STUDENT";
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS";
export const UPDATE_STUDENT_ERROR = "UPDATE_STUDENT_ERROR";

export const ADD_SCHOOL = "ADD_SCHOOL";
export const ADD_SCHOOL_SUCCESS = "ADD_SCHOOL_SUCCESS";
export const ADD_SCHOOL_ERROR = "ADD_SCHOOL_ERROR";

export const ADD_ENROLMENT = "ADD_ENROLMENT";
export const ADD_ENROLMENT_SUCCESS = "ADD_ENROLMENT_SUCCESS";
export const ADD_ENROLMENT_ERROR = "ADD_ENROLMENT_ERROR";

export const ADD_QUICK_ENROLMENT = "ADD_QUICK_ENROLMENT";
export const ADD_QUICK_ENROLMENT_SUCCESS = "ADD_QUICK_ENROLMENT_SUCCESS";
export const ADD_QUICK_ENROLMENT_ERROR = "ADD_QUICK_ENROLMENT_ERROR";

export const SUBMIT_PSYCHOMETRIC = "SUBMIT_PSYCHOMETRIC";
export const SUBMIT_PSYCHOMETRIC_SUCCESS = "SUBMIT_PSYCHOMETRIC_SUCCESS";
export const SUBMIT_PSYCHOMETRIC_ERROR = "SUBMIT_PSYCHOMETRIC_ERROR";

export const SUBMIT_PSYCHOMETRIC_ANALYSIS_MAIN = "SUBMIT_PSYCHOMETRIC_ANALYSIS_MAIN";
export const SUBMIT_PSYCHOMETRIC_ANALYSIS_MAIN_SUCCESS = "SUBMIT_PSYCHOMETRIC_ANALYSIS_MAIN_SUCCESS";
export const SUBMIT_PSYCHOMETRIC_ANALYSIS_MAIN_ERROR = "SUBMIT_PSYCHOMETRIC_ANALYSIS_MAIN_ERROR";

export const SUBMIT_INTROSPECTION = "SUBMIT_INTROSPECTION";
export const SUBMIT_INTROSPECTION_SUCCESS = "SUBMIT_INTROSPECTION_SUCCESS";
export const SUBMIT_INTROSPECTION_ERROR = "SUBMIT_INTROSPECTION_ERROR";

export const ADD_FITMENT_SCHOOLS = "ADD_FITMENT_SCHOOLS";
export const ADD_FITMENT_SCHOOLS_SUCCESS = "ADD_FITMENT_SCHOOLS_SUCCESS";
export const ADD_FITMENT_SCHOOLS_ERROR = "ADD_FITMENT_SCHOOLS_ERROR";

export const DELETE_FITMENT_SCHOOLS = "DELETE_FITMENT_SCHOOLS";
export const DELETE_FITMENT_SCHOOLS_SUCCESS = "DELETE_FITMENT_SCHOOLS_SUCCESS";
export const DELETE_FITMENT_SCHOOLS_ERROR = "DELETE_FITMENT_SCHOOLS_ERROR";

export const ADD_STUDENT_EXPERIENCE = "ADD_STUDENT_EXPERIENCE";
export const ADD_STUDENT_EXPERIENCE_SUCCESS = "ADD_STUDENT_EXPERIENCE_SUCCESS";
export const ADD_STUDENT_EXPERIENCE_ERROR = "ADD_STUDENT_EXPERIENCE_ERROR";

export const UPDATE_STUDENT_EXPERIENCE = "UPDATE_STUDENT_EXPERIENCE";
export const UPDATE_STUDENT_EXPERIENCE_SUCCESS =
  "UPDATE_STUDENT_EXPERIENCE_SUCCESS";
export const UPDATE_STUDENT_EXPERIENCE_ERROR =
  "UPDATE_STUDENT_EXPERIENCE_ERROR";

export const DELETE_STUDENT_EXPERIENCE = "DELETE_STUDENT_EXPERIENCE";
export const DELETE_STUDENT_EXPERIENCE_SUCCESS =
  "DELETE_STUDENT_EXPERIENCE_SUCCESS";
export const DELETE_STUDENT_EXPERIENCE_ERROR =
  "DELETE_STUDENT_EXPERIENCE_ERROR";

export const ADD_STUDENT_SCORE = "ADD_STUDENT_SCORE";
export const ADD_STUDENT_SCORE_SUCCESS = "ADD_STUDENT_SCORE_SUCCESS";
export const ADD_STUDENT_SCORE_ERROR = "ADD_STUDENT_SCORE_ERROR";

export const UPDATE_STUDENT_SCORE = "UPDATE_STUDENT_SCORE";
export const UPDATE_STUDENT_SCORE_SUCCESS = "UPDATE_STUDENT_SCORE_SUCCESS";
export const UPDATE_STUDENT_SCORE_ERROR = "UPDATE_STUDENT_SCORE_ERROR";

export const DELETE_STUDENT_SCORE = "DELETE_STUDENT_SCORE";
export const DELETE_STUDENT_SCORE_SUCCESS = "DELETE_STUDENT_SCORE_SUCCESS";
export const DELETE_STUDENT_SCORE_ERROR = "DELETE_STUDENT_SCORE_ERROR";

export const COMPLETE_INTROSPECTION = "COMPLETE_INTROSPECTION";
export const COMPLETE_INTROSPECTION_SUCCESS = "COMPLETE_INTROSPECTION_SUCCESS";
export const COMPLETE_INTROSPECTION_ERROR = "COMPLETE_INTROSPECTION_ERROR";

export const STATUS_ALIGN = "STATUS_ALIGN";
export const STATUS_ALIGN_SUCCESS = "STATUS_ALIGN_SUCCESS";
export const STATUS_ALIGN_ERROR = "STATUS_ALIGN_ERROR";

export const SUBMIT_APPLICATION = "SUBMIT_APPLICATION";
export const SUBMIT_APPLICATION_SUCCESS = "SUBMIT_APPLICATION_SUCCESS";
export const SUBMIT_APPLICATION_ERROR = "SUBMIT_APPLICATION_ERROR";

export const ALIGN_MENTOR = "ALIGN_MENTOR";
export const ALIGN_MENTOR_SUCCESS = "ALIGN_MENTOR_SUCCESS";
export const ALIGN_MENTOR_ERROR = "ALIGN_MENTOR_ERROR";

export const PENDING_ALIGN_MENTOR = "PENDING_ALIGN_MENTOR";
export const PENDING_ALIGN_MENTOR_SUCCESS = "PENDING_ALIGN_MENTOR_SUCCESS";
export const PENDING_ALIGN_MENTOR_ERROR = "PENDING_ALIGN_MENTOR_ERROR";

export const ALIGN_HEAD_COACH = "ALIGN_HEAD_COACH";
export const ALIGN_HEAD_COACH_SUCCESS = "ALIGN_HEAD_COACH_SUCCESS";
export const ALIGN_HEAD_COACH_ERROR = "ALIGN_HEAD_COACH_ERROR";

export const ALIGN_KAM = "ALIGN_KAM";
export const ALIGN_KAM_SUCCESS = "ALIGN_KAM_SUCCESS";
export const ALIGN_KAM_ERROR = "ALIGN_KAM_ERROR";

export const ALIGN_SALES_POC = "ALIGN_SALES_POC";
export const ALIGN_SALES_POC_SUCCESS = "ALIGN_SALES_POC_SUCCESS";
export const ALIGN_SALES_POC_ERROR = "ALIGN_SALES_POC_ERROR";

export const ADD_ESSAY = "ADD_ESSAY";
export const ADD_ESSAY_SUCCESS = "ADD_ESSAY_SUCCESS";
export const ADD_ESSAY_ERROR = "ADD_ESSAY_ERROR";

export const ADD_CASE = "ADD_CASE";
export const ADD_CASE_SUCCESS = "ADD_CASE_SUCCESS";
export const ADD_CASE_ERROR = "ADD_CASE_ERROR";

export const SUBMIT_ESSAY_VERSION = "SUBMIT_ESSAY_VERSION";
export const SUBMIT_ESSAY_VERSION_SUCCESS = "SUBMIT_ESSAY_VERSION_SUCCESS";
export const SUBMIT_ESSAY_VERSION_ERROR = "SUBMIT_ESSAY_VERSION_ERROR";

export const GET_ESSAY_VERSIONS = "GET_ESSAY_VERSIONS";
export const GET_ESSAY_VERSIONS_SUCCESS = "GET_ESSAY_VERSIONS_SUCCESS";
export const GET_ESSAY_VERSIONS_ERROR = "GET_ESSAY_VERSIONS_ERROR";

export const GET_MENTOR = "GET_MENTOR";
export const GET_MENTOR_SUCCESS = "GET_MENTOR_SUCCESS";
export const GET_MENTOR_ERROR = "GET_MENTOR_ERROR";

export const GET_COUNTRYNAME = "GET_COUNTRYNAME";
export const GET_COUNTRYNAME_SUCCESS = "GET_COUNTRYNAME_SUCCESS";
export const GET_COUNTRYNAME_ERROR = "GET_COUNTRYNAME_ERROR";

export const GET_EXPERIENCE = "GET_EXPERIENCE";
export const GET_EXPERIENCE_SUCCESS = "GET_EXPERIENCE_SUCCESS";
export const GET_EXPERIENCE_ERROR = "GET_EXPERIENCE_ERROR";

export const COMPLETE_SCHOOL_FITMENT = "COMPLETE_SCHOOL_FITMENT";
export const COMPLETE_SCHOOL_FITMENT_SUCCESS =
  "COMPLETE_SCHOOL_FITMENT_SUCCESS";
export const COMPLETE_SCHOOL_FITMENT_ERROR = "COMPLETE_SCHOOL_FITMENT_ERROR";

export const SUBMIT_SCHOOL_FITMENT = "SUBMIT_SCHOOL_FITMENT";
export const SUBMIT_SCHOOL_FITMENT_SUCCESS = "SUBMIT_SCHOOL_FITMENT_SUCCESS";
export const SUBMIT_SCHOOL_FITMENT_ERROR = "SUBMIT_SCHOOL_FITMENT_ERROR";

export const GET_STUDENT_LIST = "GET_STUDENT_LIST";
export const GET_STUDENT_LIST_SUCCESS = "GET_STUDENT_LIST_SUCCESS";
export const GET_STUDENT_LIST_ERROR = "TODO_GET_LIST_ERROR";

export const GET_PRODUCT_LIST = "GET_PRODUCT_LIST";
export const GET_PRODUCT_LIST_SUCCESS = "GET_PRODUCT_LIST_SUCCESS";
export const GET_PRODUCT_LIST_ERROR = "GET_PRODUCT_LIST_ERROR";

export const GET_PAYMENT_SOURCES = "GET_PRODUPAYMENT_SOURCES";
export const GET_PAYMENT_SOURCES_SUCCESS = "GET_PAYMENT_SOURCES_SUCCESS";
export const GET_PAYMENT_SOURCES_ERROR = "GET_PAYMENT_SOURCES_ERROR";

export const GET_BACKEND_USERS = "GET_BACKEND_USERS";
export const GET_BACKEND_USERS_SUCCESS = "GET_BACKEND_USERS_SUCCESS";
export const GET_BACKEND_USERS_ERROR = "GET_BACKEND_USERS_ERROR";

export const GET_SCORES = "GET_SCORES";
export const GET_SCORES_SUCCESS = "GET_SCORES_SUCCESS";
export const GET_SCORES_ERROR = "GET_SCORES_ERROR";

export const GET_SCHOOLS = "GET_SCHOOLS";
export const GET_SCHOOLS_SUCCESS = "GET_SCHOOLS_SUCCESS";
export const GET_SCHOOLS_ERROR = "GET_SCHOOLS_ERROR";

export const GET_History = "GET_History";
export const GET_History_SUCCESS = "GET_History_SUCCESS";
export const GET_History_ERROR = "GET_History_ERROR";

export const CUSTOM_ERROR = "CUSTOM_ERROR";
export const ADD_NOTES = "ADD_NOTES";
export const ADD_NOTES_SUCCESS = "ADD_NOTES_SUCCESS";
export const ADD_NOTES_ERROR = "ADD_NOTES_ERROR";

/* Pending Cases */
export const GET_NO_KAM_LIST = "GET_NO_KAM_LIST";
export const GET_NO_KAM_LIST_SUCCESS = "GET_NO_KAM_LIST_SUCCESS";
export const GET_NO_KAM_LIST_ERROR = "GET_NO_KAM_LIST_ERROR";

export const ADD_INTRO_LOGS = "ADD_INTRO_LOGS";
export const ADD_INTRO_LOGS_SUCCESS = "ADD_INTRO_LOGS_SUCCESS";
export const ADD_INTRO_LOGS_ERROR = "ADD_INTRO_LOGS_ERROR";

export const GET_PENDING_INTRO_LIST = "GET_PENDING_INTRO_LIST";
export const GET_PENDING_INTRO_LIST_SUCCESS = "GET_PENDING_INTRO_LIST_SUCCESS";
export const GET_PENDING_INTRO_LIST_ERROR = "GET_PENDING_INTRO_LIST_ERROR";

export const GET_PENDING_MENTOR_LIST = "GET_PENDING_MENTOR_LIST";
export const GET_PENDING_MENTOR_LIST_SUCCESS = "GET_PENDING_MENTOR_LIST_SUCCESS";
export const GET_PENDING_MENTOR_LIST_ERROR = "GET_PENDING_MENTOR_LIST_ERROR";

export const GET_PENDING_INTROSPECTION_LIST = "GET_PENDING_INTROSPECTION_LIST";
export const GET_PENDING_INTROSPECTION_LIST_SUCCESS = "GET_PENDING_INTROSPECTION_LIST_SUCCESS";
export const GET_PENDING_INTROSPECTION_LIST_ERROR = "GET_PENDING_INTROSPECTION_LIST_ERROR";

export const GET_PENDING_TEST_LIST = "GET_PENDING_TEST_LIST";
export const GET_PENDING_TEST_LIST_SUCCESS = "GET_PENDING_TEST_LIST_SUCCESS";
export const GET_PENDING_TEST_LIST_ERROR = "GET_PENDING_TEST_LIST_ERROR";

export const ALIGN_SINGLE_CASE_KAM = "ALIGN_SINGLE_CASE_KAM";
export const ALIGN_SINGLE_CASE_KAM_SUCCESS = "ALIGN_SINGLE_CASE_KAM_SUCCESS";
export const ALIGN_SINGLE_CASE_KAM_ERROR = "ALIGN_SINGLE_CASE_KAM_ERROR";

export const ALIGN_KAM_MULTI_CASE = "ALIGN_KAM_MULTI_CASE";
export const ALIGN_KAM_MULTI_CASE_SUCCESS = "ALIGN_KAM_MULTI_CASE_SUCCESS";
export const ALIGN_KAM_MULTI_CASE_ERROR = "ALIGN_KAM_MULTI_CASE_ERROR";

export const SUBMIT_PSYCHOMETRIC_TEST = "SUBMIT_PSYCHOMETRIC_TEST";
export const SUBMIT_PSYCHOMETRIC_TEST_SUCCESS = "SUBMIT_PSYCHOMETRIC_TEST_SUCCESS";
export const SUBMIT_PSYCHOMETRIC_TEST_ERROR = "SUBMIT_PSYCHOMETRIC_TEST_ERROR";

export const SUBMIT_PSYCHOMETRIC_ANALYSIS = "SUBMIT_PSYCHOMETRIC_ANALYSIS";
export const SUBMIT_PSYCHOMETRIC_ANALYSIS_SUCCESS = "SUBMIT_PSYCHOMETRIC_ANALYSIS_SUCCESS";
export const SUBMIT_PSYCHOMETRIC_ANALYSIS_ERROR = "SUBMIT_PSYCHOMETRIC_ANALYSIS_ERROR";

export const GET_PENDING_ANALYSIS_LIST = "GET_PENDING_ANALYSIS_LIST";
export const GET_PENDING_ANALYSIS_LIST_SUCCESS = "GET_PENDING_ANALYSIS_LIST_SUCCESS";
export const GET_PENDING_ANALYSIS_LIST_ERROR = "GET_PENDING_ANALYSIS_LIST_ERROR";

export const SUBMIT_PENDING_INTROSPECTION = "SUBMIT_PENDING_INTROSPECTION";
export const SUBMIT_PENDING_INTROSPECTION_SUCCESS = "SUBMIT_PENDING_INTROSPECTION_SUCCESS";
export const SUBMIT_PENDING_INTROSPECTION_ERROR = "SUBMIT_PENDING_INTROSPECTION_ERROR";

export const COMPLETE_PENDING_INTROSPECTION = "COMPLETE_PENDING_INTROSPECTION";
export const COMPLETE_PENDING_INTROSPECTION_SUCCESS = "COMPLETE_PENDING_INTROSPECTION_SUCCESS";
export const COMPLETE_PENDING_INTROSPECTION_ERROR = "COMPLETE_PENDING_INTROSPECTION_ERROR";

export const GET_PENDING_SHORTLISTING_LIST = "GET_PENDING_SHORTLISTING_LIST";
export const GET_PENDING_SHORTLISTING_LIST_SUCCESS = "GET_PENDING_SHORTLISTING_LIST_SUCCESS";
export const GET_PENDING_SHORTLISTING_LIST_ERROR = "GET_PENDING_SHORTLISTING_LIST_ERROR";

export const SUBMIT_PENDING_SCHOOL_FITMENT = "SUBMIT_PENDING_SCHOOL_FITMENT";
export const SUBMIT_PENDING_SCHOOL_FITMENT_SUCCESS = "SUBMIT_PENDING_SCHOOL_FITMENT_SUCCESS";
export const SUBMIT_PENDING_SCHOOL_FITMENT_ERROR = "SUBMIT_PENDING_SCHOOL_FITMENT_ERROR";

export const COMPLETE_PENDING_SCHOOL_FITMENT = "COMPLETE_PENDING_SCHOOL_FITMENT";
export const COMPLETE_PENDING_SCHOOL_FITMENT_SUCCESS = "COMPLETE_PENDING_SCHOOL_FITMENT_SUCCESS";
export const COMPLETE_PENDING_SCHOOL_FITMENT_ERROR = "COMPLETE_PENDING_SCHOOL_FITMENT_ERROR";

export const ADD_PENDING_FITMENT_SCHOOLS = "ADD_PENDING_FITMENT_SCHOOLS";
export const ADD_PENDING_FITMENT_SCHOOLS_SUCCESS = "ADD_PENDING_FITMENT_SCHOOLS_SUCCESS";
export const ADD_PENDING_FITMENT_SCHOOLS_ERROR = "ADD_PENDING_FITMENT_SCHOOLS_ERROR";


/* Details*/
export const GET_STUDENT_DETAILS = "GET_STUDENT";
export const GET_STUDENT_DETAILS_SUCCESS = "GET_STUDENT_SUCCESS";
export const GET_STUDENT_DETAILS_ERROR = "TODO_GET_ERROR";

/* INTALK CALL*/
export const INTALK_CALL = "INTALK_CALL";
export const INTALK_CALL_SUCCESS = "INTALK_CALL_SUCCESS";
export const INTALK_CALL_ERROR = "INTALK_CALL_ERROR";

/*Dashboard*/
export const GET_Recent_Enrolments = "GET_Recent_Enrolments";
export const GET_Recent_Enrolments_SUCCESS = "GET_Recent_Enrolments_SUCCESS";
export const GET_Recent_Enrolments_ERROR = "GET_Recent_Enrolments_ERROR";
export const GET_Dashboard_Data = "GET_Dashboard_Data";
export const GET_Dashboard_Data_SUCCESS = "GET_Dashboard_Data_SUCCESS";
export const GET_Dashboard_Data_ERROR = "GET_Dashboard_Data_ERROR";
export const GET_Enrolments_Graph = "GET_Enrolments_Graph";
export const GET_Enrolments_Graph_SUCCESS = "GET_Enrolments_Graph_SUCCESS";
export const GET_Enrolments_Graph_ERROR = "GET_Enrolments_Graph_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

/* CHAT APP*/
export const CHAT_GET_CONTACTS = "CHAT_GET_CONTACTS";
export const CHAT_GET_CONTACTS_SUCCESS = "CHAT_GET_CONTACTS_SUCCESS";
export const CHAT_GET_CONTACTS_ERROR = "CHAT_GET_CONTACTS_ERROR";
export const CHAT_GET_CONVERSATIONS = "CHAT_GET_CONVERSATIONS";
export const CHAT_GET_CONVERSATIONS_SUCCESS = "CHAT_GET_CONVERSATIONS_SUCCESS";
export const CHAT_GET_CONVERSATIONS_ERROR = "CHAT_GET_CONVERSATIONS_ERROR";
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  "CHAT_ADD_MESSAGE_TO_CONVERSATION";
export const CHAT_CREATE_CONVERSATION = "CHAT_CREATE_CONVERSATION";
export const CHAT_SEARCH_CONTACT = "CHAT_SEARCH_CONTACT";
export const CHAT_CHANGE_CONVERSATION = "CHAT_CHANGE_CONVERSATION";

/* SURVEY LIST APP*/
export const SURVEY_LIST_GET_LIST = "SURVEY_LIST_GET_LIST";
export const SURVEY_LIST_GET_LIST_SUCCESS = "SURVEY_LIST_GET_LIST_SUCCESS";
export const SURVEY_LIST_GET_LIST_ERROR = "SURVEY_LIST_GET_LIST_ERROR";
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  "SURVEY_LIST_GET_LIST_WITH_FILTER";
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  "SURVEY_LIST_GET_LIST_WITH_ORDER";
export const SURVEY_LIST_GET_LIST_SEARCH = "SURVEY_LIST_GET_LIST_SEARCH";
export const SURVEY_LIST_ADD_ITEM = "SURVEY_LIST_ADD_ITEM";
export const SURVEY_LIST_ADD_ITEM_SUCCESS = "SURVEY_LIST_ADD_ITEM_SUCCESS";
export const SURVEY_LIST_ADD_ITEM_ERROR = "SURVEY_LIST_ADD_ITEM_ERROR";
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  "SURVEY_LIST_SELECTED_ITEMS_CHANGE";

/* SURVEY DETAIL APP*/
export const SURVEY_GET_DETAILS = "SURVEY_GET_DETAILS";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const SURVEY_GET_DETAILS_ERROR = "SURVEY_GET_DETAILS_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";
export const RESET_ERRORS = "RESET_ERRORS";


export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
